OTP
Kelompok4-LoyaltyPointAgent/Backend pull request #8
Opened 2022-11-26 09:49 UTC by andikabahari

Belum:
- Send pin OTP ke email user (cek service OTP)

Sudah:
- Request pin OTP
- Verifikasi pin OTP

2022-11-26 14:56 UTC, j4ceu requested changes
Sama tolong tambahin boolean isUsed di modelnya dik, thank uu

2022-11-26 14:56 UTC, j4ceu commented on services/otp_service/otp_service.go
> +	s.otpRepository.DeleteByID(otp.ID)
ditambahin err := nya di bagian line ini dik

2022-11-27 06:38 UTC, andikabahari commented on services/otp_service/otp_service.go
> +	s.otpRepository.DeleteByID(otp.ID)
- nambah field is_used
- handle error
- delete diganti jadi update is_used = true

2022-11-27 06:40 UTC, andikabahari commented on services/otp_service/otp_service.go
> +	s.otpRepository.DeleteByID(otp.ID)
di sini [853018d](https://github.com/Kelompok4-LoyaltyPointAgent/Backend/pull/8/commits/853018d3640fe63c623cf61d5a5fa0c59be59fc0)

2022-11-27 18:41 UTC, merged